server:
  servlet:
    context-path: /terras/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://eozuchihazt:S2Fh7v8FPP.nBca@cluster0.rcbxix2.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /public/swagger


terras:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}

admin:
  init:
    nome: Administrador do Sistema
    email: georgepaulozt@gmail.com
    senha: 123456
